substitutions:
  device_name: "saunalcd"
  sauna_device_name: "tylo"
  api_encryption_key: !secret api_key_saunalcd
  ota_password: !secret ota_pass_saunalcd

  board_type: esp32-s3-devkitc-1
  flash_size: 16MB
  log_level: INFO

  display_rotation: "0"
  ui_title: "Sauna"

  climate_entity: "climate.${sauna_device_name}_sauna_climate"
  heater_switch: "switch.${sauna_device_name}_heater"
  light_switch: "switch.${sauna_device_name}_light"
  number_bath_temp: "number.${sauna_device_name}_bath_temperature"
  heating_element: "sensor.${sauna_device_name}_heating_element"

  climate_temp_min: 40
  climate_temp_max: 110

esphome:
  name: ${device_name}
  friendly_name: ${device_name}

esp32:
  board: ${board_type}
  flash_size: ${flash_size}
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

logger:
  level: ${log_level}
  baud_rate: 0

api:
  encryption:
    key: ${api_encryption_key}

ota:
  - platform: esphome
    password: ${ota_password}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

font:
  - file: "gfonts://Roboto@700"
    id: font_title
    size: 34
    glyphs: " °+-.:0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"

  - file: "gfonts://Roboto"
    id: font_big
    size: 64
    glyphs: " °+-.:0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"

  - file: "gfonts://Roboto"
    id: font_mid
    size: 26
    glyphs: " °+-.:0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"

  - file: "fonts/materialdesignicons-webfont.ttf"
    id: mdi_26
    size: 26
    bpp: 4
    glyphs:
      - "\U000F0425" # mdi-power
      - "\U000F0335" # mdi-lightbulb
      - "\U000F0336" # mdi-lightbulb-outline
      - "\U000F0E04" # mdi-thermometer-minus
      - "\U000F0E05" # mdi-thermometer-plus

globals:
  - id: ui_set_temp
    type: int
    restore_value: no
    initial_value: "0"

spi:
  id: display_qspi
  type: quad
  clk_pin: 47
  data_pins: [21, 48, 40, 39]

i2c:
  sda: 4
  scl: 8
  id: touchscreen_bus

display:
  - platform: mipi_spi
    model: JC3248W535
    bus_mode: quad
    spi_id: display_qspi
    id: my_display
    cs_pin: 45
    data_rate: 40MHz
    rotation: ${display_rotation}
    dimensions:
      height: 480
      width: 320
    auto_clear_enabled: false
    update_interval: never

output:
  - platform: ledc
    pin: 1
    id: backlight

light:
  - platform: monochromatic
    output: backlight
    name: "Backlight"
    restore_mode: ALWAYS_ON

touchscreen:
  - platform: axs15231
    id: my_touch
    display: my_display
    i2c_id: touchscreen_bus
    transform:
      swap_xy: false
      mirror_x: false
      mirror_y: false

text_sensor:
  - platform: homeassistant
    id: ha_heater_state
    entity_id: ${heater_switch}
    on_value:
      - lvgl.widget.update:
          id: sw_heater
          state:
            checked: !lambda 'return id(ha_heater_state).state == "on";'
      - if:
          condition:
            lambda: 'return id(ha_heater_state).state == "on";'
          then:
            - lvgl.widget.hide: { id: ico_power_off }
            - lvgl.widget.show: { id: ico_power_on }
          else:
            - lvgl.widget.show: { id: ico_power_off }
            - lvgl.widget.hide: { id: ico_power_on }

  - platform: homeassistant
    id: ha_light_state
    entity_id: ${light_switch}
    on_value:
      - lvgl.widget.update:
          id: sw_light
          state:
            checked: !lambda 'return id(ha_light_state).state == "on";'
      - if:
          condition:
            lambda: 'return id(ha_light_state).state == "on";'
          then:
            - lvgl.widget.hide: { id: ico_light_off }
            - lvgl.widget.show: { id: ico_light_on }
          else:
            - lvgl.widget.show: { id: ico_light_off }
            - lvgl.widget.hide: { id: ico_light_on }

sensor:
  - platform: homeassistant
    id: ha_curr_temp
    entity_id: ${climate_entity}
    attribute: current_temperature
    on_value:
      - lvgl.label.update:
          id: lbl_curr
          text: !lambda |-
            char buf[24];
            snprintf(buf, sizeof(buf), "%.0f °C", id(ha_curr_temp).state);
            return std::string(buf);

  - platform: homeassistant
    id: ha_target_temp
    entity_id: ${number_bath_temp}
    on_value:
      - lambda: |-
          id(ui_set_temp) = (int) roundf(id(ha_target_temp).state);
      - lvgl.label.update:
          id: lbl_set
          text: !lambda |-
            char buf[16];
            snprintf(buf, sizeof(buf), "%.0f °C", id(ha_target_temp).state);
            return std::string(buf);
      - lvgl.slider.update:
          id: sld_set
          value: !lambda "return (int) roundf(id(ha_target_temp).state);"

lvgl:
  draw_rounding: 8
  buffer_size: 12%
  displays: my_display
  touchscreens: my_touch
  bg_color: 0x000000
  border_width: 0
  outline_width: 0

  style_definitions:
    # Switch-Track
    - id: st_sw_track
      radius: 18
      bg_color: 0x2A2F38 # darkgrey (OFF)

    - id: st_sw_track_on
      radius: 18
      bg_color: 0xC8CCD1 # lightgrey (ON)

    # Switch-Indicator
    - id: st_sw_ind_off
      bg_opa: 0% # OFF

    - id: st_sw_ind_on
      bg_opa: 0% # ON

    - id: st_sw_knob
      bg_color: 0xFFFFFF

    # Slider
    - id: st_sld_track
      radius: 14
      bg_color: 0x3A7BFF
      bg_grad_color: 0xFF3A2A
      bg_grad_dir: HOR
      bg_opa: 25%
      border_width: 1
      border_color: 0x2A2F38

    - id: st_sld_ind_temp
      bg_color: 0x3A7BFF
      bg_grad_color: 0xFF3A2A
      bg_grad_dir: HOR

    - id: st_sld_knob
      bg_color: 0xFFFFFF

    # Label-Background
    - id: st_lblbg_big
      bg_color: 0x000000
      bg_opa: 100%
      pad_left: 6
      pad_right: 6
      pad_top: 2
      pad_bottom: 2

    - id: st_lblbg_mid
      bg_color: 0x000000
      bg_opa: 100%
      pad_left: 6
      pad_right: 6
      pad_top: 2
      pad_bottom: 2

    # Buttons
    - id: st_btn_inc
      bg_color: 0xCCCCCC

    - id: st_btn_dec
      bg_color: 0xCCCCCC

    - id: st_btn_base
      radius: 10
      bg_color: 0x2A2F38
      bg_opa: 100%
      border_width: 0
      clip_corner: true
      pad_left: 0
      pad_right: 0
      pad_top: 0
      pad_bottom: 0

    - id: st_btn_pressed
      radius: 10
      bg_color: 0x3A4452
      bg_opa: 100%
      border_width: 0
      clip_corner: true
      pad_left: 0
      pad_right: 0
      pad_top: 0
      pad_bottom: 0

    # Icon-Color
    - id: st_icon_power_off
      text_color: 0xFFFFFF # white (OFF)

    - id: st_icon_power_on
      text_color: 0xFF7A00 # orange (ON)

    - id: st_icon_light_off
      text_color: 0xFFFFFF # white (OFF)

    - id: st_icon_light_on
      text_color: 0xFFD000 # yellow (ON)

  pages:
    - id: main_page
      widgets:
        - label:
            text: "${ui_title}"
            align: TOP_MID
            text_align: CENTER
            y: 10
            width: 320
            text_color: 0xFFFFFF
            text_font: font_title
            styles: [st_lblbg_big]

        - label:
            id: lbl_curr
            text: "-- °C"
            align: TOP_MID
            text_align: CENTER
            y: 60
            width: 320
            text_color: 0xFFFFFF
            text_font: font_big
            styles: [st_lblbg_big]

        - label:
            id: lbl_set
            text: "- - °C"
            align: TOP_MID
            text_align: CENTER
            y: 150
            width: 320
            text_color: 0xFFFFFF
            text_font: font_mid
            styles: [st_lblbg_mid]

        - label:
            id: ico_power_off
            text: "\U000F0425" # mdi:power
            text_font: mdi_26
            align: TOP_LEFT
            x: 14
            y: 224
            styles: [st_icon_power_off]

        - label:
            id: ico_power_on
            text: "\U000F0425" # mdi:power
            text_font: mdi_26
            align: TOP_LEFT
            x: 14
            y: 224
            styles: [st_icon_power_on]

        - switch:
            id: sw_heater
            align: TOP_LEFT
            x: 54
            y: 220
            width: 66
            height: 36
            styles: [st_sw_track]
            checked:
              styles: [st_sw_track_on]
            indicator:
              styles: [st_sw_ind_off]
              checked:
                styles: [st_sw_ind_on]
            knob:
              styles: [st_sw_knob]
            on_value:
              - if:
                  condition:
                    lambda: "return (bool) x;"
                  then:
                    - lvgl.widget.hide: { id: ico_power_off }
                    - lvgl.widget.show: { id: ico_power_on }
                  else:
                    - lvgl.widget.show: { id: ico_power_off }
                    - lvgl.widget.hide: { id: ico_power_on }
              - if:
                  condition:
                    lambda: |-
                      const bool ui_on = (bool) x;
                      const bool ha_on = (id(ha_heater_state).state == "on");
                      return ui_on != ha_on;
                  then:
                    - homeassistant.service:
                        service: !lambda 'return x ? "switch.turn_on" : "switch.turn_off";'
                        data:
                          entity_id: ${heater_switch}

        - label:
            id: ico_light_off
            text: "\U000F0336" # mdi:lightbulb-outline
            text_font: mdi_26
            align: TOP_LEFT
            x: 178
            y: 224
            styles: [st_icon_light_off]

        - label:
            id: ico_light_on
            text: "\U000F0336" # mdi:lightbulb-outline
            text_font: mdi_26
            align: TOP_LEFT
            x: 178
            y: 224
            styles: [st_icon_light_on]

        - switch:
            id: sw_light
            align: TOP_LEFT
            x: 214
            y: 220
            width: 66
            height: 36
            styles: [st_sw_track]
            checked:
              styles: [st_sw_track_on]
            indicator:
              styles: [st_sw_ind_off]
              checked:
                styles: [st_sw_ind_on]
            knob:
              styles: [st_sw_knob]
            on_value:
              - if:
                  condition:
                    lambda: "return (bool) x;"
                  then:
                    - lvgl.widget.hide: { id: ico_light_off }
                    - lvgl.widget.show: { id: ico_light_on }
                  else:
                    - lvgl.widget.show: { id: ico_light_off }
                    - lvgl.widget.hide: { id: ico_light_on }
              - if:
                  condition:
                    lambda: |-
                      const bool ui_on = (bool) x;
                      const bool ha_on = (id(ha_light_state).state == "on");
                      return ui_on != ha_on;
                  then:
                    - homeassistant.service:
                        service: !lambda 'return x ? "switch.turn_on" : "switch.turn_off";'
                        data:
                          entity_id: ${light_switch}

        - button:
            id: btn_dec
            align: TOP_MID
            x: -80
            y: 310
            width: 64
            height: 48
            styles: [st_btn_base]
            pressed:
              styles: [st_btn_pressed]
            widgets:
              - label:
                  text: "\U000F0E04"
                  align: CENTER
                  text_font: mdi_26
            on_press:
              - lambda: |-
                  int v = id(ui_set_temp);
                  if (v > ${climate_temp_min}) v -= 1;
                  id(ui_set_temp) = v;
              - lvgl.slider.update:
                  id: sld_set
                  value: !lambda "return id(ui_set_temp);"
              - lvgl.label.update:
                  id: lbl_set
                  text: !lambda |-
                    char buf[16];
                    snprintf(buf, sizeof(buf), "%d °C", id(ui_set_temp));
                    return std::string(buf);
              - homeassistant.service:
                  service: number.set_value
                  data:
                    entity_id: ${number_bath_temp}
                    value: !lambda "return (float) id(ui_set_temp);"

        - button:
            id: btn_inc
            align: TOP_MID
            x: 80
            y: 310
            width: 64
            height: 48
            styles: [st_btn_base]
            pressed:
              styles: [st_btn_pressed]
            widgets:
              - label:
                  text: "\U000F0E05"
                  align: CENTER
                  text_font: mdi_26
            on_press:
              - lambda: |-
                  int v = id(ui_set_temp);
                  if (v < ${climate_temp_max}) v += 1;
                  id(ui_set_temp) = v;
              - lvgl.slider.update:
                  id: sld_set
                  value: !lambda "return id(ui_set_temp);"
              - lvgl.label.update:
                  id: lbl_set
                  text: !lambda |-
                    char buf[16];
                    snprintf(buf, sizeof(buf), "%d °C", id(ui_set_temp));
                    return std::string(buf);
              - homeassistant.service:
                  service: number.set_value
                  data:
                    entity_id: ${number_bath_temp}
                    value: !lambda "return (float) id(ui_set_temp);"

        - slider:
            id: sld_set
            align: BOTTOM_MID
            y: -40
            width: 240
            min_value: ${climate_temp_min}
            max_value: ${climate_temp_max}
            styles: [st_sld_track]
            indicator:
              styles: [st_sld_ind_temp]
            knob:
              styles: [st_sld_knob]
            on_value:
              - lambda: |-
                  id(ui_set_temp) = (int) x;
              - lvgl.label.update:
                  id: lbl_set
                  text: !lambda |-
                    char buf[16];
                    snprintf(buf, sizeof(buf), "%d °C", (int) x);
                    return std::string(buf);
            on_release:
              - homeassistant.service:
                  service: number.set_value
                  data:
                    entity_id: ${number_bath_temp}
                    value: !lambda "return (float) x;"
