# COMBI overlay:
sensor:
  - platform: sauna360
    humidity_setting:
      name: "Setting Humidity Step"   # 0–10
  - platform: sauna360 
    water_level: 
      name: "Water Tank Level"

number:
  - platform: sauna360
    humidity_step:
      name: "Humidity Step"           # 0–10
      mode: box
      humidity_step_default: 1