# COMBI overlay (Steps 0–10)
sensor:
  - platform: sauna360
    setting_humidity_step:
      name: "Setting Humidity Step"
  - platform: sauna360
    water_tank_level:
      name: "Water Tank Level"

number:
  - platform: sauna360
    humidity_step:
      name: "Humidity Step"
      mode: box
      humidity_step_default: ${default_humidity_step}
